version: 2
updates:
  - package-ecosystem: "npm" # updates package.json dependencies
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions" # updates github actions
    directory: "/"
    schedule:
      interval: "weekly"
